name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  generate_diagram:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          config_path: diagram-config.json
      - name: Upload diagram to repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-diagram
          path: diagram.svg